//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationEvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateBirthday { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public string Gender { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
